import type { AppLanguage } from './app-language';

export const DESKTOP_COPY = {
  en: {
    header: {
      dashboard: 'Dashboard',
      dashboardDesc: 'Live view of workload, field capacity, and billing readiness.',
      dispatch: 'Dispatch',
      dispatchDesc: 'Assign work, balance routes, and recover the queue.',
      technicians: 'Technicians',
      techniciansDesc: 'Availability, skills, and workload across the field team.',
      workOrders: 'Work Orders',
      workOrdersDesc: 'Track the full lifecycle of active and completed jobs.',
      clients: 'Clients',
      clientsDesc: 'Customer accounts, service history, and account health.',
      billing: 'Billing',
      billingDesc: 'Sales orders, approvals, and invoice readiness.',
      reports: 'Reports',
      reportsDesc: 'Operational and financial reporting across the workspace.',
      search: 'Search',
      searchDesc: 'Find jobs, customers, and sales orders quickly.',
      mobilePreview: 'Mobile Preview',
      mobilePreviewDesc: 'Preview the technician mobile experience.',
      schedule: 'Schedule',
      scheduleDesc: 'Calendar view.',
    },
    dashboard: {
      operationsOverview: 'Operations overview',
      serviceCommandDesk: 'Service command desk',
      installationCommandDesk: 'Installation command desk',
      liveWorkload: 'Live workload for',
      keepSync: 'Keep queue health, technician capacity, and billing movement in sync.',
      openDispatch: 'Open dispatch',
      newWorkOrder: 'New work order',
      jobsToday: 'Jobs today',
      scheduledVisits: 'Scheduled visits on the board today.',
      openWork: 'Open work',
      jobsMoving: 'Jobs still moving through dispatch or execution.',
      revenueMTD: 'Revenue MTD',
      bookedSalesOrder: 'Booked sales order value this month.',
      avgDuration: 'Avg duration',
      averageCompleted: 'Average completed job duration in the workspace.',
      todaySchedule: "Today's schedule",
      firstPassView: 'First-pass view of the workload already committed for today.',
      manageSchedule: 'Manage schedule',
      noWorkOrdersToday: 'No work orders scheduled today',
      useDispatch: 'Use the dispatch board to assign work and build the route.',
      recentActivity: 'Recent activity',
      latestJobUpdates: 'Latest job updates and operational movement.',
      job: 'Job',
      customer: 'Customer',
      status: 'Status',
      priority: 'Priority',
      updated: 'Updated',
      revenueThisMonth: 'Revenue this month',
      weeklyBooked: 'Weekly booked sales order movement.',
      dispatchPriorities: 'Dispatch priorities',
      firstPlaces: 'The first places to focus next.',
      unassignedWork: 'Unassigned work',
      jobsWaiting: 'Jobs waiting for a technician or route slot.',
      slaRisk: 'SLA risk',
      workOrdersIntervention: 'Work orders that need intervention before the customer window slips.',
      followUpRequired: 'Follow-up required',
      completedVisits: 'Completed visits that still need a callback, revisit, or confirmation.',
      readyToBill: 'Ready to bill',
      operationalWork: 'Operational work ready for sales order review.',
      fieldCoverage: 'Field coverage',
      techniciansLoad: 'Technicians with current load in the active workspace.',
      generalFieldCoverage: 'General field coverage',
      openJobs: 'Open jobs',
      workMix: 'Work mix',
      currentLoad: 'Where the current load is concentrated.',
      byStatus: 'By status',
      byServiceType: 'By service type',
    },
    jobList: {
      exportCSV: 'Export CSV',
      newJob: '+ New Job',
      allJobs: 'All Jobs',
      today: 'Today',
      open: 'Open',
      overdue: 'Overdue',
      billing: 'Billing',
      searchJobs: 'Search jobs…',
      allStatuses: 'All Statuses',
      allPriorities: 'All Priorities',
      allTypes: 'All Types',
      allTechnicians: 'All Technicians',
      allAssignments: 'All Assignments',
      allFocusAreas: 'All Focus Areas',
      assigned: 'Assigned',
      unassigned: 'Unassigned',
      slaRisk: 'SLA Risk',
      followUpRequired: 'Follow-up Required',
      warranty: 'Warranty',
      missingSchedule: 'Missing Schedule',
      clearFilters: 'Clear filters',
      jobNumber: 'Job #',
      customer: 'Customer',
      description: 'Description',
      status: 'Status',
      priority: 'Priority',
      type: 'Type',
      scheduled: 'Scheduled',
      technician: 'Technician',
      salesOrder: 'Sales Order',
      noJobsFound: 'No jobs found',
      tryAdjusting: 'Try adjusting your filters',
      serviceJobs: 'Service Jobs',
      installationProjects: 'Installation Projects',
      results: 'results',
    },
    jobDetail: {
      summary: 'Summary',
      scheduling: 'Scheduling',
      time: 'Time',
      parts: 'Parts',
      checklist: 'Checklist',
      notes: 'Notes',
      salesOrder: 'Sales Order',
      files: 'Files',
      billing: 'Billing',
      history: 'History',
      jobNotFound: 'Job not found',
      jobMayHaveBeenRemoved: 'This job may have been removed or you may not have access.',
      backToJobs: 'Back to Jobs',
      slaBreached: 'SLA breached — this job requires immediate attention.',
      onHold: 'This job is currently on hold.',
      warranty: 'This job is covered under warranty.',
      edit: 'Edit',
      reassignTech: 'Reassign Tech',
      assignTech: 'Assign Tech',
    },
    jobForm: {
      jobs: 'Jobs',
      newJob: 'New Job',
      createNewJob: 'Create New Job',
      unsavedChanges: 'You have unsaved changes',
      customer: 'Customer',
      description: 'Description',
      priority: 'Priority',
      serviceType: 'Service Type',
      scheduledDate: 'Scheduled Date',
      technician: 'Technician',
      saveChanges: 'Save Changes',
      createJob: 'Create Job',
      cancel: 'Cancel',
    },
    schedule: {
      schedule: 'Schedule',
      weeklyCalendar: 'Weekly calendar view across technicians with quick reschedule controls.',
      newJob: '+ New Job',
      scheduledThisWeek: 'Scheduled This Week',
      sameDayJobs: 'Same Day Jobs',
      unassigned: 'Unassigned',
      technicians: 'Technicians',
      prev: '← Prev',
      today: 'Today',
      next: 'Next →',
      technician: 'Technician',
      noJobs: 'No jobs',
      timeTBD: 'Time TBD',
      reschedule: 'Reschedule',
      newDate: 'New Date',
      startTime: 'Start Time',
      endTime: 'End Time',
      reason: 'Reason',
      whyRescheduled: 'Why is this job being rescheduled?',
    },
    technicians: {
      fieldCoverage: 'Field coverage',
      technicianWorkspace: 'Technician workspace',
      availableNow: 'Available now',
      techniciansReady: 'Technicians ready for immediate assignment.',
      onJob: 'On job',
      crewMembers: 'Crew members actively executing assigned work.',
      activeLoad: 'Active load',
      openAssigned: 'Open assigned jobs across the workspace.',
      avgLoadTech: 'Avg load / tech',
      averageWorkload: 'Average active workload per technician.',
      searchByName: 'Search by name, email, or skill',
      allRegions: 'All regions',
      clearFilters: 'Clear filters',
      noTechniciansMatch: 'No technicians match the current filters',
      tryWidening: 'Try widening the search or clearing filters.',
      noTechniciansAvailable: 'No technicians are available in this workspace.',
      skills: 'Skills',
      updateStatus: 'Update status',
      currentStatus: 'Current status:',
      current: 'Current',
    },
    billing: {
      billing: 'Billing',
      pendingReview: 'Pending review, billing-ready queues, warranty jobs, and sales-order controls.',
      bulkBillingReady: 'Bulk Billing Ready',
      generateInvoices: 'Generate Invoices',
      newJobSO: '+ New Job / SO',
      pendingReviewTab: 'Pending Review',
      billingReadyTab: 'Billing Ready',
      warrantyOpen: 'Warranty Open',
      pendingBalance: 'Pending Balance',
      warrantyJobs: 'Warranty Jobs',
      salesOrders: 'Sales Orders',
      noJobsInQueue: 'No jobs in this queue',
      everythingCleared: 'Everything in this billing queue has been cleared.',
      jobNumber: 'Job #',
      customer: 'Customer',
      type: 'Type',
      completed: 'Completed',
      technician: 'Technician',
      labor: 'Labor',
      parts: 'Parts',
      total: 'Total',
      billingColumn: 'Billing',
      actions: 'Actions',
      review: 'Review',
      markReady: 'Mark Ready',
      invoice: 'Invoice',
      hold: 'Hold',
      removeHold: 'Remove Hold',
      warranty: 'Warranty',
      allStatuses: 'All Statuses',
      searchSalesOrders: 'Search sales orders…',
      soNumber: 'SO #',
      memo: 'Memo',
      status: 'Status',
      date: 'Date',
      balance: 'Balance',
      linkedJob: 'Linked Job',
      noSalesOrdersFound: 'No sales orders found',
      billingHold: 'Billing Hold',
      reason: 'Reason',
      whyOnHold: 'Why is this job on billing hold?',
      putOnHold: 'Put on Hold',
      newSalesOrder: 'New Sales Order',
      customerRequired: 'Customer *',
      searchCustomers: 'Search customers…',
      briefSummary: 'Brief summary for this sales order…',
      createSalesOrder: 'Create Sales Order',
      backToBilling: 'Back to Billing',
    },
    reports: {
      reports: 'Reports',
      serviceOperations: 'Service Operations',
      installationProjects: 'Installation Projects',
      analytics: 'Analytics',
      last7Days: 'Last 7 days',
      last30Days: 'Last 30 days',
      last90Days: 'Last 90 days',
      lastYear: 'Last year',
      overview: 'Overview',
      jobs: 'Jobs',
      revenue: 'Revenue',
      technicians: 'Technicians',
      customers: 'Customers',
      totalJobs: 'Total Jobs',
      completed: 'Completed',
      completionRate: 'Completion Rate',
      slaBreached: 'SLA Breached',
      warrantyJobs: 'Warranty Jobs',
      readyToBill: 'Ready to Bill',
      followUps: 'Follow-ups',
      avgDuration: 'Avg Duration',
      jobsByStatus: 'Jobs by Status',
      jobsByServiceType: 'Jobs by Service Type',
      revenueTrend: 'Revenue Trend',
      trendRolledUp: 'Trend rolled up across the last',
      days: 'days',
      jobsByPriority: 'Jobs by Priority',
      jobCompletionTable: 'Job Completion Table',
      status: 'Status',
      count: 'Count',
      financialOutput: 'Financial output for the last',
      revenueSummary: 'Revenue Summary',
      totalSORevenue: 'Total SO Revenue',
      fullyBilled: 'Fully Billed',
      outstanding: 'Outstanding',
      technicianPerformance: 'Technician Performance',
      totalJobsLegend: 'Total Jobs',
      technician: 'Technician',
      total: 'Total',
      rate: 'Rate',
      topCustomers: 'Top Customers by Job Count',
      customer: 'Customer',
    },
    search: {
      search: 'Search',
      searchPlaceholder: 'Search customers, jobs, sales orders, addresses…',
      searchEverything: 'Search Everything',
      searchByDescription: 'Search by customer name, job number, address, city, postal code, sales order number, contact info, or any description text.',
      searching: 'Searching…',
      noResultsFor: 'No results for',
      tryBroader: 'Try a broader search term or check your spelling.',
      resultsFor: 'results for',
      customers: 'Customers',
      jobs: 'Jobs',
      salesOrders: 'Sales Orders',
    },
    clients: {
      clients: 'Clients',
      customers: 'customers',
      searchPlaceholder: 'Search by name, phone, email, address…',
      allCategories: 'All Categories',
      clear: 'Clear',
      noClientsFound: 'No clients found',
      tryDifferent: 'Try a different search term.',
      inactive: 'Inactive',
      jobs: 'Jobs',
      open: 'Open',
      since: 'Since',
    },
    clientDetail: {
      clients: 'Clients',
      clientNotFound: 'Client not found',
      backToClients: 'Back to Clients',
      overview: 'Overview',
      newJob: '+ New Job',
      editClient: 'Edit Client',
      contactInformation: 'Contact Information',
      entityId: 'Entity ID',
      company: 'Company',
      contact: 'Contact',
      email: 'Email',
      phone: 'Phone',
      altPhone: 'Alt Phone',
      website: 'Website',
      accountNumber: 'Account #',
      category: 'Category',
      customerSince: 'Customer Since',
      note: 'Note',
      addresses: 'Addresses',
      defaultBadge: 'Default',
      shipBadge: 'Ship',
      billBadge: 'Bill',
      recentJobs: 'Recent Jobs',
      viewAll: 'View all →',
      noJobsYet: 'No jobs yet',
      recentSalesOrders: 'Recent Sales Orders',
      noSalesOrders: 'No sales orders',
      jobNumber: 'Job #',
      description: 'Description',
      status: 'Status',
      priority: 'Priority',
      type: 'Type',
      scheduled: 'Scheduled',
      technician: 'Technician',
      salesOrder: 'Sales Order',
      noJobs: 'No jobs',
      soNumber: 'SO #',
      memo: 'Memo',
      date: 'Date',
      total: 'Total',
      linkedJob: 'Linked Job',
      fileName: 'File Name',
      source: 'Source',
      uploaded: 'Uploaded',
      by: 'By',
      noFilesFound: 'No files found',
      noFilesAttached: 'No job or sales-order files are attached to this customer yet.',
      noAssetsOnRecord: 'No assets on record',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      allJobs: 'All Jobs',
      salesOrders: 'Sales Orders',
      files: 'Files',
      assets: 'Assets',
    },
  },
  fr: {
    header: {
      dashboard: 'Tableau de bord',
      dashboardDesc: 'Vue en temps réel de la charge, capacité terrain et facturation.',
      dispatch: 'Répartition',
      dispatchDesc: 'Assigner le travail, équilibrer les routes et récupérer la file.',
      technicians: 'Techniciens',
      techniciansDesc: "Disponibilité, compétences et charge de l'équipe terrain.",
      workOrders: 'Bons de travail',
      workOrdersDesc: 'Suivre le cycle complet des travaux actifs et terminés.',
      clients: 'Clients',
      clientsDesc: 'Comptes clients, historique de service et santé du compte.',
      billing: 'Facturation',
      billingDesc: 'Commandes clients, approbations et prêt à facturer.',
      reports: 'Rapports',
      reportsDesc: "Rapports opérationnels et financiers de l'espace de travail.",
      search: 'Recherche',
      searchDesc: 'Trouver rapidement des travaux, clients et commandes.',
      mobilePreview: 'Aperçu mobile',
      mobilePreviewDesc: "Aperçu de l'expérience mobile du technicien.",
      schedule: 'Calendrier',
      scheduleDesc: 'Vue calendrier.',
    },
    dashboard: {
      operationsOverview: 'Aperçu des opérations',
      serviceCommandDesk: 'Bureau de commande service',
      installationCommandDesk: 'Bureau de commande installation',
      liveWorkload: 'Charge en temps réel pour le',
      keepSync: 'Gardez la file, la capacité terrain et la facturation synchronisées.',
      openDispatch: 'Ouvrir la répartition',
      newWorkOrder: 'Nouveau bon de travail',
      jobsToday: "Travaux aujourd'hui",
      scheduledVisits: "Visites planifiées au tableau aujourd'hui.",
      openWork: 'Travaux en cours',
      jobsMoving: "Travaux en cours de répartition ou d'exécution.",
      revenueMTD: 'Revenus du mois',
      bookedSalesOrder: 'Valeur des commandes confirmées ce mois.',
      avgDuration: 'Durée moy.',
      averageCompleted: 'Durée moyenne des travaux terminés.',
      todaySchedule: "Horaire d'aujourd'hui",
      firstPassView: "Vue initiale de la charge déjà confirmée pour aujourd'hui.",
      manageSchedule: "Gérer l'horaire",
      noWorkOrdersToday: "Aucun bon de travail planifié aujourd'hui",
      useDispatch: 'Utilisez le tableau de répartition pour assigner et planifier.',
      recentActivity: 'Activité récente',
      latestJobUpdates: 'Dernières mises à jour des travaux.',
      job: 'Travail',
      customer: 'Client',
      status: 'Statut',
      priority: 'Priorité',
      updated: 'Mis à jour',
      revenueThisMonth: 'Revenus ce mois',
      weeklyBooked: 'Évolution hebdomadaire des commandes.',
      dispatchPriorities: 'Priorités de répartition',
      firstPlaces: 'Les premiers points à traiter.',
      unassignedWork: 'Travaux non assignés',
      jobsWaiting: "Travaux en attente d'un technicien.",
      slaRisk: 'Risque SLA',
      workOrdersIntervention: 'Bons nécessitant une intervention avant dépassement.',
      followUpRequired: 'Suivi requis',
      completedVisits: 'Visites terminées nécessitant un suivi.',
      readyToBill: 'Prêt à facturer',
      operationalWork: 'Travaux prêts pour révision de commande.',
      fieldCoverage: 'Couverture terrain',
      techniciansLoad: 'Techniciens avec charge active.',
      generalFieldCoverage: 'Couverture terrain générale',
      openJobs: 'Travaux ouverts',
      workMix: 'Répartition des travaux',
      currentLoad: 'Où la charge est concentrée.',
      byStatus: 'Par statut',
      byServiceType: 'Par type de service',
    },
    jobList: {
      exportCSV: 'Exporter CSV',
      newJob: '+ Nouveau travail',
      allJobs: 'Tous les travaux',
      today: "Aujourd'hui",
      open: 'En cours',
      overdue: 'En retard',
      billing: 'Facturation',
      searchJobs: 'Rechercher des travaux…',
      allStatuses: 'Tous les statuts',
      allPriorities: 'Toutes les priorités',
      allTypes: 'Tous les types',
      allTechnicians: 'Tous les techniciens',
      allAssignments: 'Toutes les assignations',
      allFocusAreas: 'Tous les axes',
      assigned: 'Assigné',
      unassigned: 'Non assigné',
      slaRisk: 'Risque SLA',
      followUpRequired: 'Suivi requis',
      warranty: 'Garantie',
      missingSchedule: 'Sans horaire',
      clearFilters: 'Effacer les filtres',
      jobNumber: 'Bon #',
      customer: 'Client',
      description: 'Description',
      status: 'Statut',
      priority: 'Priorité',
      type: 'Type',
      scheduled: 'Planifié',
      technician: 'Technicien',
      salesOrder: 'Commande',
      noJobsFound: 'Aucun travail trouvé',
      tryAdjusting: "Essayez d'ajuster vos filtres",
      serviceJobs: 'Travaux de service',
      installationProjects: "Projets d'installation",
      results: 'résultats',
    },
    jobDetail: {
      summary: 'Résumé',
      scheduling: 'Planification',
      time: 'Temps',
      parts: 'Pièces',
      checklist: 'Liste de contrôle',
      notes: 'Notes',
      salesOrder: 'Commande',
      files: 'Fichiers',
      billing: 'Facturation',
      history: 'Historique',
      jobNotFound: 'Travail introuvable',
      jobMayHaveBeenRemoved: "Ce travail a peut-être été supprimé ou vous n'y avez pas accès.",
      backToJobs: 'Retour aux travaux',
      slaBreached: 'SLA dépassé — ce travail nécessite une attention immédiate.',
      onHold: 'Ce travail est actuellement en attente.',
      warranty: 'Ce travail est couvert par la garantie.',
      edit: 'Modifier',
      reassignTech: 'Réassigner le technicien',
      assignTech: 'Assigner le technicien',
    },
    jobForm: {
      jobs: 'Travaux',
      newJob: 'Nouveau travail',
      createNewJob: 'Créer un nouveau travail',
      unsavedChanges: 'Vous avez des modifications non sauvegardées',
      customer: 'Client',
      description: 'Description',
      priority: 'Priorité',
      serviceType: 'Type de service',
      scheduledDate: 'Date planifiée',
      technician: 'Technicien',
      saveChanges: 'Sauvegarder',
      createJob: 'Créer le travail',
      cancel: 'Annuler',
    },
    schedule: {
      schedule: 'Calendrier',
      weeklyCalendar: 'Vue calendrier hebdomadaire avec contrôles de replanification.',
      newJob: '+ Nouveau travail',
      scheduledThisWeek: 'Planifiés cette semaine',
      sameDayJobs: 'Travaux du jour',
      unassigned: 'Non assignés',
      technicians: 'Techniciens',
      prev: '← Préc.',
      today: "Aujourd'hui",
      next: 'Suiv. →',
      technician: 'Technicien',
      noJobs: 'Aucun travail',
      timeTBD: 'Heure à confirmer',
      reschedule: 'Replanifier',
      newDate: 'Nouvelle date',
      startTime: 'Heure de début',
      endTime: 'Heure de fin',
      reason: 'Raison',
      whyRescheduled: 'Pourquoi ce travail est-il replanifié?',
    },
    technicians: {
      fieldCoverage: 'Couverture terrain',
      technicianWorkspace: 'Espace technicien',
      availableNow: 'Disponible maintenant',
      techniciansReady: 'Techniciens prêts pour une assignation immédiate.',
      onJob: 'En travail',
      crewMembers: 'Membres actifs exécutant les travaux assignés.',
      activeLoad: 'Charge active',
      openAssigned: 'Travaux assignés ouverts.',
      avgLoadTech: 'Charge moy. / tech.',
      averageWorkload: 'Charge active moyenne par technicien.',
      searchByName: 'Rechercher par nom, courriel ou compétence',
      allRegions: 'Toutes les régions',
      clearFilters: 'Effacer les filtres',
      noTechniciansMatch: 'Aucun technicien ne correspond aux filtres',
      tryWidening: "Essayez d'élargir la recherche.",
      noTechniciansAvailable: 'Aucun technicien disponible dans cet espace.',
      skills: 'Compétences',
      updateStatus: 'Mettre à jour le statut',
      currentStatus: 'Statut actuel :',
      current: 'Actuel',
    },
    billing: {
      billing: 'Facturation',
      pendingReview: "File d'attente de révision, facturation prête, travaux sous garantie et commandes.",
      bulkBillingReady: 'Facturation groupée prête',
      generateInvoices: 'Générer des factures',
      newJobSO: '+ Nouveau travail / Commande',
      pendingReviewTab: 'En attente de révision',
      billingReadyTab: 'Prêt à facturer',
      warrantyOpen: 'Garantie ouverte',
      pendingBalance: 'Solde en attente',
      warrantyJobs: 'Travaux sous garantie',
      salesOrders: 'Commandes clients',
      noJobsInQueue: 'Aucun travail dans cette file',
      everythingCleared: 'Tout a été traité dans cette file de facturation.',
      jobNumber: 'Bon #',
      customer: 'Client',
      type: 'Type',
      completed: 'Terminé',
      technician: 'Technicien',
      labor: "Main-d'œuvre",
      parts: 'Pièces',
      total: 'Total',
      billingColumn: 'Facturation',
      actions: 'Actions',
      review: 'Réviser',
      markReady: 'Marquer prêt',
      invoice: 'Facturer',
      hold: 'Retenir',
      removeHold: 'Retirer la retenue',
      warranty: 'Garantie',
      allStatuses: 'Tous les statuts',
      searchSalesOrders: 'Rechercher des commandes…',
      soNumber: 'Commande #',
      memo: 'Note',
      status: 'Statut',
      date: 'Date',
      balance: 'Solde',
      linkedJob: 'Travail lié',
      noSalesOrdersFound: 'Aucune commande trouvée',
      billingHold: 'Retenue de facturation',
      reason: 'Raison',
      whyOnHold: 'Pourquoi ce travail est-il en retenue?',
      putOnHold: 'Mettre en retenue',
      newSalesOrder: 'Nouvelle commande',
      customerRequired: 'Client *',
      searchCustomers: 'Rechercher des clients…',
      briefSummary: 'Résumé bref pour cette commande…',
      createSalesOrder: 'Créer la commande',
      backToBilling: 'Retour à la facturation',
    },
    reports: {
      reports: 'Rapports',
      serviceOperations: 'Opérations de service',
      installationProjects: "Projets d'installation",
      analytics: 'Analytique',
      last7Days: '7 derniers jours',
      last30Days: '30 derniers jours',
      last90Days: '90 derniers jours',
      lastYear: 'Dernière année',
      overview: 'Aperçu',
      jobs: 'Travaux',
      revenue: 'Revenus',
      technicians: 'Techniciens',
      customers: 'Clients',
      totalJobs: 'Total des travaux',
      completed: 'Terminés',
      completionRate: 'Taux de complétion',
      slaBreached: 'SLA dépassé',
      warrantyJobs: 'Travaux sous garantie',
      readyToBill: 'Prêt à facturer',
      followUps: 'Suivis',
      avgDuration: 'Durée moy.',
      jobsByStatus: 'Travaux par statut',
      jobsByServiceType: 'Travaux par type',
      revenueTrend: 'Tendance des revenus',
      trendRolledUp: 'Tendance sur les',
      days: 'derniers jours',
      jobsByPriority: 'Travaux par priorité',
      jobCompletionTable: 'Tableau de complétion',
      status: 'Statut',
      count: 'Nombre',
      financialOutput: 'Résultats financiers des',
      revenueSummary: 'Sommaire des revenus',
      totalSORevenue: 'Revenus totaux des commandes',
      fullyBilled: 'Entièrement facturé',
      outstanding: 'En attente',
      technicianPerformance: 'Performance des techniciens',
      totalJobsLegend: 'Total des travaux',
      technician: 'Technicien',
      total: 'Total',
      rate: 'Taux',
      topCustomers: 'Meilleurs clients par nombre de travaux',
      customer: 'Client',
    },
    search: {
      search: 'Recherche',
      searchPlaceholder: 'Rechercher clients, travaux, commandes, adresses…',
      searchEverything: 'Recherche globale',
      searchByDescription: 'Recherchez par nom de client, numéro de bon, adresse, ville, code postal, numéro de commande, coordonnées ou description.',
      searching: 'Recherche…',
      noResultsFor: 'Aucun résultat pour',
      tryBroader: "Essayez un terme plus large ou vérifiez l'orthographe.",
      resultsFor: 'résultats pour',
      customers: 'Clients',
      jobs: 'Travaux',
      salesOrders: 'Commandes',
    },
    clients: {
      clients: 'Clients',
      customers: 'clients',
      searchPlaceholder: 'Rechercher par nom, téléphone, courriel, adresse…',
      allCategories: 'Toutes les catégories',
      clear: 'Effacer',
      noClientsFound: 'Aucun client trouvé',
      tryDifferent: 'Essayez un autre terme.',
      inactive: 'Inactif',
      jobs: 'Travaux',
      open: 'Ouverts',
      since: 'Depuis',
    },
    clientDetail: {
      clients: 'Clients',
      clientNotFound: 'Client introuvable',
      backToClients: 'Retour aux clients',
      overview: 'Aperçu',
      newJob: '+ Nouveau travail',
      editClient: 'Modifier le client',
      contactInformation: 'Coordonnées',
      entityId: 'ID entité',
      company: 'Entreprise',
      contact: 'Contact',
      email: 'Courriel',
      phone: 'Téléphone',
      altPhone: 'Tél. alternatif',
      website: 'Site web',
      accountNumber: 'N° de compte',
      category: 'Catégorie',
      customerSince: 'Client depuis',
      note: 'Note',
      addresses: 'Adresses',
      defaultBadge: 'Par défaut',
      shipBadge: 'Livraison',
      billBadge: 'Facturation',
      recentJobs: 'Travaux récents',
      viewAll: 'Voir tout →',
      noJobsYet: 'Aucun travail',
      recentSalesOrders: 'Commandes récentes',
      noSalesOrders: 'Aucune commande',
      jobNumber: 'Bon #',
      description: 'Description',
      status: 'Statut',
      priority: 'Priorité',
      type: 'Type',
      scheduled: 'Planifié',
      technician: 'Technicien',
      salesOrder: 'Commande',
      noJobs: 'Aucun travail',
      soNumber: 'Commande #',
      memo: 'Note',
      date: 'Date',
      total: 'Total',
      linkedJob: 'Travail lié',
      fileName: 'Nom du fichier',
      source: 'Source',
      uploaded: 'Téléversé',
      by: 'Par',
      noFilesFound: 'Aucun fichier trouvé',
      noFilesAttached: 'Aucun fichier attaché à ce client.',
      noAssetsOnRecord: 'Aucun actif enregistré',
      saveChanges: 'Sauvegarder',
      cancel: 'Annuler',
      allJobs: 'Tous les travaux',
      salesOrders: 'Commandes',
      files: 'Fichiers',
      assets: 'Actifs',
    },
  },
} as const;

export type DesktopCopy = typeof DESKTOP_COPY['en'];

export function getDesktopCopy(language: AppLanguage) {
  return DESKTOP_COPY[language];
}
